### PR TITLE
Use all interfaces with AWS ENI allocator

### PR DESCRIPTION
**Pull request by kopiczko**
Towards https://github.com/giantswarm/giantswarm/issues/29164

### CODE REVIEW

**Review by ced0ps — APPROVED** [review]
LGTMIT

**Comment by ubergesundheit** [comment]
Is this also broken in the upstream repository? Or is GS doing something that makes this change GS only. I could not find the file in the upstream repositoy so I assume the latter

**Comment by ubergesundheit** [comment]
Sorry for writing not precise enough. I wasn't refering to failing CI checks but the actual changes in the template.

**Comment by kopiczko** [comment]
`install/kubernetes/cilium/templates/cilium-cni-configmap.yaml` doesn't exist upstream

**Comment by kopiczko** [comment]
Closing. Explanations in https://github.com/giantswarm/giantswarm/issues/29164#issuecomment-1849466959

**Pull request closed without merging**
